# Generated by Django 6.0 on 2026-04-24 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('Starter', 'Starter'), ('Soup', 'Soup'), ('Salad', 'Salad'), ('Main Course', 'Main Course'), ('Breads', 'Breads'), ('Rice & Biryani', 'Rice & Biryani'), ('Dessert', 'Dessert'), ('Drinks', 'Drinks')], max_length=20),
        ),
    ]
